[package]
name = "wordle_yvaniak"
description = "wordle game in rust for learning"
version = "2.0.0"
license = "MIT"
edition = "2021"

[dependencies]
rand = "0.10.2"                                    #pour le choix random du mot
unicode-segmentation = "1.13.3"                    #pour la comparaison entre charactères qui semblent humains avec les accent
clap = { version = "4.6.1", features = ["cargo"] }
cliclack = "0.5.5"                                 #surement temporaire
colored = "3.1.1"

[dev-dependencies]
assert_cmd = "2.2.2"

[[bin]]
name = "wordle"
path = "src/main.rs"
